### ISSUE TITLE
Prefix your class name to avoid conflicts

### ISSUE THREAD

**Issue by raphrmx** [getyourway/flutter_gyw#7]
Hello,

It would be better to prefix your public (exported) classes from your plugin to avoid conflicts with other classes from application.

Example your BTDevice class or BTManager class.

It would be better than GYWBTDevice or GYWBTManager.

Cheers,
Raph from PnP.

**Comment by TheToto42** [comment]
Hello,

This is a very good idea, I'm going to implement it in the future release !

Thanks,
